version: '3.1'
services:
  face_recognizer:
    image: face_recognizer
    container_name: face_recognizer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./:/face_recognizer
      - keras_cache:/root/.keras


volumes:
  keras_cache: